Modify getDataset repository API call to use 'excludeFiles' parameter
IQSS/dataverse-client-javascript pull request #112
Opened 2024-01-03 14:49 UTC by GPortas

## What this PR does / why we need it:

## Which issue(s) this PR closes:

- Closes #

## Related Dataverse PRs:

- Depends on #

## Special notes for your reviewer:

## Suggestions on how to test this:

## Is there a release notes update needed for this change?:

## Additional documentation:

2024-01-03 19:40 UTC, ekraffmiller requested changes
Hi Guillermo, I tried this PR against the SPA, and it is still not getting the deaccessioned dataset when the user has logged out. Can you add a test for that?

2024-01-03 19:40 UTC, ekraffmiller commented on test/integration/datasets/DatasetsRepository.test.ts
For the tests, can you add a test to get the deaccessioned dataset when the user has logged out? That is the use case that we need to support in the SPA.

2024-01-04 14:00 UTC, GPortas commented
@ekraffmiller 

I just added a test for the scenario you mention, but it is failing due to the API issue I explain on `dv-tech`.

2024-01-04 17:19 UTC, GPortas commented
Waiting for: https://github.com/IQSS/dataverse/issues/10207

2024-02-05 01:41 UTC, ekraffmiller approved these changes
looks good!

2024-02-06 11:36 UTC, MellyGray approved these changes
QA ✅

2024-02-06 11:37 UTC, merged