109 - Add totalFilesCount to GetDatasetFiles use case
IQSS/dataverse-client-javascript pull request #116
Opened 2024-01-17 16:25 UTC by MellyGray

## What this PR does / why we need it:
This PR introduces `totalFilesCount` to the `GetDatasetFiles` use case, which is essential for pagination. This ensures consistency with the pagination implementation, as seen in `DatasetPreviewSubset`.

## Which issue(s) this PR closes:

- Closes #109 

## Related Dataverse PRs:

- Depends on https://github.com/IQSS/dataverse/issues/10202

## Special notes for your reviewer:
The implementation should be consistent with GetAllDatasetPreviews implementation, so just compare the code with that use case

## Suggestions on how to test this:
Run integration tests or review GitHub action execution

2024-01-23 13:37 UTC, GPortas requested changes
Looks good.

We need also to export the `FilesSubset` model in the `index.ts` file of the files folder, [just as we do with the `DatasetPreviewSubset`](https://github.com/IQSS/dataverse-client-javascript/blob/develop/src/datasets/index.ts#L47)

2024-01-24 09:18 UTC, MellyGray commented
> Looks good.
> 
> We need also to export the `FilesSubset` model in the `index.ts` file of the files folder, [just as we do with the `DatasetPreviewSubset`](https://github.com/IQSS/dataverse-client-javascript/blob/develop/src/datasets/index.ts#L47)

I addressed the change. But I'm worried about what would had happened if you hadn't noticed. I think that somehow we need some tests to test the package from the outside. To force the check on these index exports, and  also ensure that the package functions properly when used as a library

2024-01-24 10:22 UTC, GPortas commented
> > Looks good.
> > We need also to export the `FilesSubset` model in the `index.ts` file of the files folder, [just as we do with the `DatasetPreviewSubset`](https://github.com/IQSS/dataverse-client-javascript/blob/develop/src/datasets/index.ts#L47)
> 
> I addressed the change. But I'm worried about what would had happened if you hadn't noticed. I think that somehow we need some tests to test the package from the outside. To force the check on these index exports, and also ensure that the package functions properly when used as a library

Yes. There is an open issue related to functional tests that would be useful for what you mention: https://github.com/IQSS/dataverse-client-javascript/issues/81

I just updated the issue to link to this comment.

2024-01-24 10:23 UTC, GPortas reviewed
Sorry, I forgot to submit this review.

Can you check the comment?

2024-01-24 10:23 UTC, GPortas commented on src/files/infra/repositories/transformers/fileTransformers.ts
> +  filesPayload.forEach(function (filesPayload: any) {
Why have you changed the name of the variable inside the function from singular to plural?

Now we have `transformFilePayloadToFile(filesPayload)` which makes it a little confusing.

2024-01-24 15:38 UTC, MellyGray commented on src/files/infra/repositories/transformers/fileTransformers.ts
> +  filesPayload.forEach(function (filesPayload: any) {
My bad, I committed the change

2024-01-24 19:05 UTC, GPortas approved these changes

2024-01-31 15:15 UTC, merged