122 - Extend dataset and file models to contain owner information
IQSS/dataverse-client-javascript pull request #127
Opened 2024-02-20 11:27 UTC by MellyGray

## What this PR does / why we need it:
This PR extends the payload of the dataset and file model to add a new owner property with the owner information of the object.

## Which issue(s) this PR closes:

- Closes #122

## Related Dataverse PRs:

- Depends on https://github.com/IQSS/dataverse/issues/10286

## Special notes for your reviewer:
I also added some types for the file and dataset payload to avoid using any.

## Suggestions on how to test this:
1. Visual inspection of the code
2. Check the tests running

## Is there a release notes update needed for this change?:
Dataset and file models extended to add object owner information

## Additional documentation:

2024-02-27 16:29 UTC, GPortas requested changes
Some early feedback, understanding that you have pending changes to implement. Thanks.

2024-02-27 16:29 UTC, GPortas commented on src/datasets/infra/repositories/transformers/datasetTransformers.ts
> +      return metadataFieldValuePayload.map((v) => transformPayloadToDatasetMetadataSubfieldValue(v));
Minor detail - Can we rename "v" to something more understandable?

2024-02-27 16:29 UTC, GPortas commented on src/datasets/infra/repositories/transformers/datasetTransformers.ts
> +  return metadataFieldsPayload.reduce((acc: DatasetMetadataFields, field: MetadataFieldPayload) => {
Minor detail - Can we rename "acc" to something more understandable? Like `datasetMetadataFieldsResult` or simply `result`

2024-02-27 16:29 UTC, GPortas commented on src/dv-object/domain/models/DvObjectOwnerNode.ts
> +export interface DvObjectOwnerNode {
I don't think dv-object should be considered as a sub-domain in the package. I would place this file and any other dvObject related file in the core subdomain, as the dvObject is a concept shared across the different subdomains (collections, files and datasets).

2024-02-28 07:47 UTC, MellyGray commented on src/datasets/infra/repositories/transformers/datasetTransformers.ts
> +  return metadataFieldsPayload.reduce((acc: DatasetMetadataFields, field: MetadataFieldPayload) => {
I don't like `result` because it means finished, but the variable in this case is the accumulator so it's not really the result until the reduce it's finished, I rename it to `datasetMetadataFieldsMap`, hope that's ok

2024-02-28 10:12 UTC, GPortas approved these changes
LGTM

2024-02-28 10:12 UTC, merged