197 compare dataset versions
IQSS/dataverse-client-javascript pull request #220
Opened 2024-11-14 15:19 UTC by ekraffmiller

## What this PR does / why we need it:
Creates use case for comparing Dataset versions

## Which issue(s) this PR closes:

- Closes #197 

## Related Dataverse PRs:

- Depends on #

## Special notes for your reviewer:

## Suggestions on how to test this:

## Is there a release notes update needed for this change?:

## Additional documentation:

2024-11-21 22:31 UTC, ChengShi-1 requested changes
I left some comments here mostly about formatting. Please check them~

2024-11-21 22:31 UTC, ChengShi-1 commented on src/datasets/infra/repositories/transformers/DatasetVersionDiffPayload.ts
I'm not sure but we may want to remove the comments here?

2024-11-21 22:31 UTC, ChengShi-1 commented on src/datasets/infra/repositories/transformers/datasetVersionDiffTransformers.ts
> + oldVersion: VersionSummaryPayload
I think those comments are good to be removed

2024-11-21 22:31 UTC, ChengShi-1 commented on test/integration/datasets/DatasetsRepository.test.ts
> +    test('should return dataset metadata diff between two dataset versions', async () => {
It may need an empty line before test() block.

2024-11-21 22:31 UTC, ChengShi-1 commented on test/integration/datasets/DatasetsRepository.test.ts
> +    test('should return added file diff between two dataset versions', async () => {
may need an empty line before test() block

2024-11-21 22:31 UTC, ChengShi-1 commented on test/integration/datasets/DatasetsRepository.test.ts
> +    test('should return  diff between :latestPublished and :draft', async () => {
may need an empty line before test() block

2024-11-21 22:31 UTC, ChengShi-1 commented on test/unit/datasets/GetDatasetVersionDiff.test.ts
> +
there is an extra empty line between two imports could be removed

2024-11-21 22:31 UTC, ChengShi-1 commented on test/integration/datasets/DatasetsRepository.test.ts
> +    afterEach(async () => {
may need an empty line before afterEach() block

2024-11-21 22:31 UTC, ChengShi-1 commented on test/integration/datasets/DatasetsRepository.test.ts
> +      expect(actual.metadataChanges[0].blockName).toEqual('Citation Metadata')
My code editor(vscode) has a warning for line 496 from typescript type checking or eslint. " 'actual.metadataChanges' is possibly 'undefined'."

2024-11-21 22:31 UTC, ChengShi-1 commented on src/datasets/domain/models/DatasetVersionDiff.ts
> +// Details API
not sure if this comment is needed or we could remove?

2024-11-25 14:24 UTC, ekraffmiller commented
thanks @ChengShi-1 ! I addressed your comments and removed the waiting tag, since the Dataverse API change was merged

2024-11-25 20:17 UTC, ChengShi-1 approved these changes
Great job, thanks! Approve. (I found one piece of comment didn't get remove so I just did it with a new commit.)

2024-11-26 17:56 UTC, ofahimIQSS commented
Merging PR - tests are passing.

2024-11-26 17:56 UTC, merged